/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FormDemoRouteImport } from './routes/form-demo'
import { Route as AsyncDemoRouteImport } from './routes/async-demo'
import { Route as IndexRouteImport } from './routes/index'

const FormDemoRoute = FormDemoRouteImport.update({
  id: '/form-demo',
  path: '/form-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AsyncDemoRoute = AsyncDemoRouteImport.update({
  id: '/async-demo',
  path: '/async-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/async-demo': typeof AsyncDemoRoute
  '/form-demo': typeof FormDemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/async-demo': typeof AsyncDemoRoute
  '/form-demo': typeof FormDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/async-demo': typeof AsyncDemoRoute
  '/form-demo': typeof FormDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/async-demo' | '/form-demo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/async-demo' | '/form-demo'
  id: '__root__' | '/' | '/async-demo' | '/form-demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsyncDemoRoute: typeof AsyncDemoRoute
  FormDemoRoute: typeof FormDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/form-demo': {
      id: '/form-demo'
      path: '/form-demo'
      fullPath: '/form-demo'
      preLoaderRoute: typeof FormDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/async-demo': {
      id: '/async-demo'
      path: '/async-demo'
      fullPath: '/async-demo'
      preLoaderRoute: typeof AsyncDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsyncDemoRoute: AsyncDemoRoute,
  FormDemoRoute: FormDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
